version: '3.8'

services:
  text-linker-backend:
    image: ghcr.io/liita-lod/text-linker/backend:latest
    # build: .
    ports:
      - "8000:8000"
    environment:
      - STANZA_RESOURCES_URL=${STANZA_RESOURCES_URL:-https://example.com/download/stanza_resources.tgz}
      - STANZA_RESOURCES_DIR=${STANZA_RESOURCES_DIR:-stanza_resources}
      - DATABASE_URL=${DATABASE_URL:-mysql+pymysql://username:password@host:port/database}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-*}
    volumes:
      - ./stanza_resources:/app/stanza_resources
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
