[project]
name = "liita-textlinker-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.104.0",
  "pydantic>=2.5.0",
  "pymysql>=1.1.1",
  "sqlalchemy>=2.0.41",
  "stanza>=1.10.1",
  "uvicorn[standard]>=0.24.0",
]

