import { Box, Paper, TextField, Typography } from '@mui/material';
import type React from 'react';
import { useEffect } from 'react';
import type { StepProps } from '../../types';

const InputLinking: React.FC<StepProps> = ({ data, onDataChange }) => {
  useEffect(() => {
    // Update parent component when data changes
    onDataChange({ linking: data.linking || '' });
  }, []);

  const handleLinkingChange = (
    e: React.ChangeEvent<HTMLTextAreaElement>,
  ): void => {
    onDataChange({ linking: e.target.value });
  };

  return (
    <Paper
      elevation={0}
      sx={{
        p: 3,
        background: 'rgba(255, 255, 255, 0.05)',
        backdropFilter: 'blur(10px)',
      }}
    >
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" component="h3" sx={{ mb: 1 }}>
          Step 3: Input Linking
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Review and edit the linking data automatically generated by the
          prelinker service.
        </Typography>
      </Box>

      <Box sx={{ mb: 3 }}>
        <TextField
          multiline
          rows={8}
          value={data.linking || ''}
          onChange={handleLinkingChange}
          placeholder="Linking data will be automatically generated from the prelinker service..."
          fullWidth
          variant="outlined"
          label="Linking Data (Auto-generated)"
          sx={{
            '& .MuiOutlinedInput-root': {
              backgroundColor: 'rgba(255, 255, 255, 0.05)',
              backdropFilter: 'blur(10px)',
              border: '1px solid rgba(255, 255, 255, 0.2)',
              '&:hover': {
                border: '1px solid rgba(255, 255, 255, 0.3)',
              },
              '&.Mui-focused': {
                border: '2px solid #6366f1',
              },
            },
            '& .MuiInputBase-input': {
              color: '#ffffff',
              fontFamily: 'monospace',
              fontSize: '0.875rem',
              '&::placeholder': {
                color: 'rgba(255, 255, 255, 0.5)',
                opacity: 1,
              },
            },
            '& .MuiInputLabel-root': {
              color: 'rgba(255, 255, 255, 0.7)',
            },
          }}
        />
      </Box>

      <Box>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
          <strong>Automatic Linking:</strong> The prelinker service has
          automatically generated linking data from your CoNLL-U input.
        </Typography>

        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
          <strong>Manual Editing:</strong> You can review and edit the linking
          data above if needed.
        </Typography>

        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
          <strong>Linking Format:</strong> The data connects tokens with
          external linguistic resources, knowledge bases, or lexical databases.
        </Typography>

        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
          <strong>Example Format:</strong>
        </Typography>

        <Box
          component="pre"
          sx={{
            backgroundColor: 'rgba(0, 0, 0, 0.3)',
            p: 2,
            borderRadius: 1,
            overflow: 'auto',
            fontSize: '0.875rem',
            fontFamily: 'monospace',
            border: '1px solid rgba(255, 255, 255, 0.1)',
          }}
        >
          {`token_id:1 -> resource:LiLaLemma -> lemma_id:latin_cat
token_id:2 -> resource:LiLaBrill -> brill_id:brill_cat_noun
token_id:3 -> resource:LiLaIGVL -> igvl_id:igvl_sit_verb`}
        </Box>
      </Box>
    </Paper>
  );
};

export default InputLinking;
