import { Box, Typography } from '@mui/material';
import type React from 'react';
import { useEffect, useState } from 'react';
import type { StepProps } from '../../types';
import InputActions from './InputActions';

const InputLinking: React.FC<StepProps> = ({ data, onDataChange }) => {
  const [isLoading, setIsLoading] = useState<boolean>(false);

  useEffect(() => {
    // Update parent component when data changes
    onDataChange({ linking: data.linking || '' });
  }, []);

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      <Box>
        <Typography variant="h4" component="h3" sx={{ mb: 1 }}>
          Step 3: Input Linking
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Review and edit the linking data automatically generated by the prelinker service.
        </Typography>
      </Box>

            <InputActions
        onDataChange={onDataChange}
        dataKey="linking"
        value={data.linking || ''}
        isLoading={isLoading}
        setIsLoading={setIsLoading}
        acceptFileTypes=".conllu"
        placeholder="Enter your annotated CoNLL-U data here or drag & drop a file..."
        dragPlaceholder="Drop your linking file here..."
        rows={10}
        showTextField={true}
        showOutputButtons={true}
        defaultFileName="input-linking"
      />
    </Box>
  );
};

export default InputLinking;
