import { Box, Typography } from '@mui/material';
import type React from 'react';
import { useEffect, useState } from 'react';
import type { StepProps } from '../../types';
import InputActions from '../InputActions';
import { parse, serialize as unparse, type ConlluDocument } from '../../utils/conllu';

const Linked: React.FC<StepProps> = ({ data, mergeWizardData }) => {
  const [parsedData, setParsedData] = useState<ConlluDocument | null>(null);

  useEffect(() => {
    if (data.linked) {
      try {
        setParsedData(parse(data.linked));
      } catch (error) {
        console.error('Error parsing linking data:', error);
        setParsedData(null);
      }
    } else {
      setParsedData(null);
    }
  }, [data.linked]);

  const handleDataChange = (value: string) => {
    try {
      setParsedData(parse(value));
      mergeWizardData('linked', value);
    } catch (error) {
      console.error('Error parsing input data:', error);
      setParsedData(null);
      mergeWizardData('linked', null);
    }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      <Box>
        <Typography variant="h4" component="h3" sx={{ mb: 1 }}>
          Step 3: Input Linking
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Review and edit the linking data automatically generated by the
          prelinker service.
        </Typography>
      </Box>

      <InputActions
        acceptFileTypes=".conllu"
        defaultFileName="input-linking"
        dragPlaceholder="Drop your linking file here..."
        onDataChange={handleDataChange}
        placeholder="Enter your annotated CoNLL-U data here or drag & drop a file..."
        rows={10}
        showOutputButtons={true}
        showTextField={true}
        value={parsedData ? unparse(parsedData) : ''}
      />
    </Box>
  );
};

export default Linked;
